template:
  sensor:
  - name: "count"
    state:  "{{ exists(\"count\") }}" 
    unit: "Litres"
    trigger:
      - platform: event
        event_name: "Event 1"
  - name: "count_number_2"
    state: "{{3}}" # '{{ count_number_2 + 1 }}'
    unit: "Litres"
    trigger:
      - platform: event
        event_name: "Event 2"
      